### ISSUE TITLE
how to disable libary?

### ISSUE THREAD

**Issue by Mastrom10** [gauntface/dpad-navigation#5]
i need to disable the navigation, but i dont find any window.dpadFocusController.disable()
i tried window.dpadFocusController = null, but not working.
any ideas?
ty!!!!

**Comment by gauntface** [comment]
I've just done a re-write of the library using Typescript and cleaning up the code as part of that I've just added a quick hack to disable the library.

```
window.dpad.disable();
```

All this does is prevent the focus state from moving as the result of a keypress. It should add / remove the key event listeners to make the library more lean.
